### ISSUE TITLE
ThinkCache库官方未在维护，tag和序列化问题待解决

### ISSUE THREAD

**Issue by kyour-cn** [webman-php/think-cache#2]
> tag缓存使用存在问题，php8.1中默认序列化方法存在异常等问题。

是否可以将tp内置的cache代码独立出来放到这个包，不再引用官方cache组件，如果可行的话我来创建pr

**Comment by walkor** [comment]
发pr吧

**Comment by kyour-cn** [comment]
已换laravel-cache，抱歉暂时有些忙
